# Generated by Django 4.2.1 on 2023-06-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category1',
            new_name='category',
        ),
    ]
