# Generated by Django 4.2.1 on 2023-06-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart2',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product2',
            new_name='product',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='CartItem',
        ),
    ]
